don't require `python {{ python_min }}` in testing; breaks `downstreams:` usage
conda-forge/conda-smithy-feedstock pull request #331
Opened 2024-11-21 13:21 UTC by h-vetinari

This breaks `downstreams:` testing in `conda`, see https://github.com/conda-forge/conda-feedstock/pull/243

2024-11-21 14:54 UTC, beckermr requested changes
Please do not merge. There must be another way. We can absolutely run conda on python 3.9.

2024-11-21 18:08 UTC, beckermr commented
closing since I fixed this in the upstream package

2024-11-22 03:24 UTC, h-vetinari commented
> Please do not merge. There must be another way. We can absolutely run conda on python 3.9.

Yeah, that's not the issue, it's that we need to test it against `py>39` as well, which is prohibited by the pin here.

> The tests here skip the probematic tests on windows

That should be modified to
```
      {% if py>=311 -%}
      -k "not test_lint_recipe_parses"
      {%- endif %}
```

2024-11-22 03:28 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint --conda-forge .` from the recipe directory. You can also examine the [workflow logs](https://github.com/conda-forge/conda-forge-webservices/actions/runs/11965899801) for more detail.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/11965899801](https://github.com/conda-forge/conda-forge-webservices/actions/runs/11965899801). Examine the logs at this URL for more detail.</sub>

2024-11-22 03:32 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipe/meta.yaml**:

 * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
   - For the `test.requires` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
   - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).
 * ℹ️ The recipe is not parsable by parser `conda-souschef (grayskull)`. Your recipe may not receive automatic updates and/or may not be compatible with conda-forge's infrastructure. Please check the logs for more information and ensure your recipe can be parsed.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/11965939654](https://github.com/conda-forge/conda-forge-webservices/actions/runs/11965939654). Examine the logs at this URL for more detail.</sub>

2024-11-22 03:55 UTC, h-vetinari commented
Failure here on linux is unrelated to the changes:
```
FAILED tests/test_lint_recipe.py::TestLinter::test_maintainer_team_exists - AssertionError: 'Recipe maintainer team "conda-forge/blahblahblah-foobarblah" does not exist' not found in ['The home item is expected in the about section.', 'The license item is expected in the about section.', 'The summary item is expected in the about section.', 'The recipe must have some tests.', 'The recipe must have a `build/number` section.', 'Recipe name has invalid characters. only lowercase alpha, numeric, underscores, hyphens and dots allowed', 'Package version is missing.']
```
I think this test depends on reachability of the GH API for the org-level data, which can fail? I've restared but the failure reappeared. Restarting again.

2024-11-22 04:05 UTC, beckermr requested changes
Now we're skipping the linting tests on all platforms. We should be running them.

2024-11-22 04:06 UTC, beckermr requested changes
Also the whole goal of the python min variable is to test packages on the oldest python to ensure they work there. No we're skipping that too.

2024-11-22 04:08 UTC, h-vetinari commented
> Now we're skipping the linting tests on all platforms. We should be running them.

Right, that was my intention.

> Also the whole goal of the python min variable is to test packages on the oldest python to ensure they work there. No we're skipping that too.

That however _was_ my intention. I consider the downstream tests of `conda` more important than testing with the oldest python version here (which we were fine without for the last years as well).

2024-11-22 04:13 UTC, h-vetinari commented
usage of `python_min` here is at odds with also wanting to use `conda-forge-tick` and `conda-recipe-manager` as test dependencies, since they both require 3.11. That fact alone rules out `python_min` for the test section IMO.

Either we increase `python_min=3.11` to match, or we need to make those packages compatible with a lower python, or (as this PR proposes), we just leave out the `python_min` in the test section, as in the pre-`python_min` days.

2024-11-22 04:15 UTC, h-vetinari commented
Though in this case the additional overriding concern is that `downstreams:` usage in `conda` takes precedence over `python_min` testing to me. So even if everything here ran through on 3.9, I still think we should remove `python_min` in the test section.

2024-11-22 09:44 UTC, wolfv commented
Or move to v1? :)

2024-11-22 09:46 UTC, jaimergp commented
> Or move to v1? :)

Ah, it can run several test stages, right?

2024-11-22 09:48 UTC, jaimergp commented
If folks really want several tests in `conda-build`, we could get by with some more Smithy work to parametrize test stages via `conda-build --test` and additional CI workflows. This way we could build against `>={python_min` and then test against `python {{ os.environ.get("CI_PYTHON_MIN", python_min) }}`, with `CI_PYTHON_MIN` being defined in the CI matrix. But that'll require a bit of work.

2024-11-22 10:03 UTC, h-vetinari commented
> A (bad) alternative is to make this package non-noarch and build/test as a matrix. The `downstream` design is not perfect so we are going to run into limitations with the amount of workarounds required to test something.

Yeah, I get that this is a bit of an annoying limitation of CFEP-25. We want to use the oldest python version for testing (reasonable!), but with the current setup this creates a permanent pin from the POV of the conda metadata for the testing portion of the package. Ideally we could run with the oldest python here _without_ creating that metadata constraint...

> Or move to v1? :)

Can you illustrate a bit more how that would resolve the situation?

2024-11-22 10:05 UTC, wolfv commented
@h-vetinari you can have multiple independent tests in v1 recipes: https://github.com/conda-forge/conda-feedstock/pull/244

python min should not affect downstream tests in the slightest in v1 recipes.

2024-11-22 10:11 UTC, h-vetinari commented
> python min should not affect downstream tests in the slightest in v1 recipes.

How does that work? My understanding is that if anything, smithy would need to move to v1, not conda, because it's smithy that currently hard-codes the test-requirement of `python 3.9`. Or what am I missing?

> you can have multiple independent tests in v1 recipes

I can understand that part conceptually. This should also make it possible to run against both newest and oldest python versions here, right?

2024-11-22 10:58 UTC, beckermr commented
The v1 spec specifies that if a downstream test's env is not solvable, it is skipped? This would be required in order for it to work properly, right?

2024-11-22 11:03 UTC, h-vetinari commented
> The v1 spec specifies that if a downstream test's env is not solvable, it is skipped?

Skipping the downstream test would be easy in v0 as well - just put an extra condition in the selector. My point was that I'd like to keep the downstream tests running, especially for something as low-level as the interaction between conda and conda-smithy.

2024-11-22 11:06 UTC, beckermr commented
I was asking how v1 specifies that part of the test suite for a downstream test can be skipped. 

In any case, I'll unblock this and we can pick back up the discussion later if we have the energy.

2024-11-22 11:06 UTC, beckermr approved these changes

2024-11-22 11:15 UTC, merged

2024-11-22 11:15 UTC, conda-forge-admin commented
Hi! This is the friendly conda-forge automerge bot!

I considered the following status checks when analyzing this PR:
 - **linter**: passed
 - **azure**: passed


Thus the PR was passing and merged! Have a great day!